global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'jenkins-rollback-webhook'

receivers:
  - name: 'jenkins-rollback-webhook'
    webhook_configs:
      - url: 'http://100.50.10.159:8080/generic-webhook-trigger/invoke?token=ROLLBACK_894A65_TOKEN'
        send_resolved: false
        http_config:
          basic_auth:
            username: 'admin'
            password: 'JENKINS_API_TOKEN_PLACEHOLDER'
